stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - make
  tags: 
    - gcc5

test:
  stage: test
  script:
    - make test
  tags:
    - gcc5

deploy:
  stage: deploy
  script:
    - deploy grnn GeneralRegressionNeuralNetwork
  tags:
    - gcc5
